language: rust
script:
    - git clone https://github.com/sfackler/rust-phf.git ../rust-phf
    - pushd ../rust-phf/phf
    - cargo build --verbose
    - popd
    - cargo build --verbose --all
    - pushd engine
    - cargo test --verbose --all
    - popd
    - cargo test --verbose --all
