[package]
name = "rust-text-adventure"
version = "0.1.0"
authors = ["ru-lai <ru.lai.development@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
yew = "0.7"
lazy_static = "0.1.*"
phf = { features = ["macros"], path="../rust-phf/phf" }
