[package]
authors = ["Tyler Boright <ru.lai.development@gmail.com>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[dependencies]
lazy_static = "0.1.*"
phf = { features = ["macros"], path="../../rust-phf/phf" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
